#pragma once
#include <iostream>
#include <vector>
#include <memory>
#include <string>
#include <cstring>
#include <thread>
#include <mutex>
#include <filesystem>
#include "miniaudio.h"
#include "notcurses/notcurses.h"
#include "notcurses/nckeys.h"
